-- 카테고리
INSERT INTO waste_categories (id, name_ko, bin_type, color, sort_order) VALUES
  ('pet', '페트', '투명 페트 전용함', '#2563EB', 1),
  ('plastic', '플라스틱', '플라스틱 수거함', '#3B82F6', 2),
  ('can', '캔', '캔 수거함', '#60A5FA', 3),
  ('glass', '유리', '유리 수거함', '#1D4ED8', 4),
  ('paper', '종이', '종이 수거함', '#93C5FD', 5),
  ('vinyl', '비닐', '비닐 수거함', '#38BDF8', 6),
  ('food', '음식물', '음식물 전용 수거함', '#0284C7', 7),
  ('general', '일반쓰레기', '종량제 봉투', '#64748B', 8),
  ('battery', '폐건전지', '폐건전지 수거함', '#1E40AF', 9),
  ('medicine', '폐의약품', '약국·보건소 폐의약품 수거함', '#1D4ED8', 10),
  ('small_electronics', '소형가전', '소형가전 수거함', '#2563EB', 11),
  ('clothing', '의류', '의류 수거함', '#3B82F6', 12);

-- 품목
INSERT INTO waste_items (id, category_id, name_ko, summary_ko, special_bin_type, is_active) VALUES
  ('pet-clear', 'pet', '투명 페트병', '내용물을 비우고 라벨을 제거한 뒤 압착하세요.', NULL, 1),
  ('pet-colored', 'pet', '유색 페트병', '투명 페트와 분리하고, 내용물을 비운 뒤 플라스틱으로 배출하세요.', NULL, 1),
  ('plastic-container', 'plastic', '플라스틱 용기', '음식물을 헹구고 라벨을 제거한 뒤 플라스틱으로 배출하세요.', NULL, 1),
  ('vinyl-bag', 'vinyl', '비닐봉투', '이물질을 털고 흩날리지 않게 모아 비닐로 배출하세요.', NULL, 1),
  ('alu-can', 'can', '알루미늄 캔', '내용물을 비우고 눌러 납작하게 만든 뒤 캔으로 배출하세요.', NULL, 1),
  ('steel-can', 'can', '철캔', '내용물을 비우고 이물질을 제거한 뒤 캔으로 배출하세요.', NULL, 1),
  ('glass-bottle', 'glass', '유리병', '내용물을 비우고 깨지지 않게 유리로 배출하세요. 뚜껑은 분리합니다.', NULL, 1),
  ('paper-box', 'paper', '종이박스', '테이프와 운송장을 떼고 접어서 종이로 배출하세요.', NULL, 1),
  ('newspaper', 'paper', '신문', '물기에 젖지 않게 묶거나 박스에 담아 종이로 배출하세요.', NULL, 1),
  ('food-waste', 'food', '음식물 쓰레기', '물기를 최대한 제거하고 음식물 전용 수거함에 넣으세요.', NULL, 1),
  ('general-waste', 'general', '일반쓰레기', '재활용이 안 되는 오염된 쓰레기는 종량제 봉투에 넣으세요.', NULL, 1),
  ('battery', 'battery', '폐건전지', '일반쓰레기로 버리지 말고 전용 수거함에 모으세요.', 'battery', 1),
  ('medicine', 'medicine', '폐의약품', '싱크대나 쓰레기통에 버리지 말고 약국 수거함에 가져가세요.', 'medicine', 1),
  ('small-electronics', 'small_electronics', '소형가전', '케이블을 정리해 소형가전 수거함이나 재활용 정거장에 배출하세요.', 'electronics', 1),
  ('clothing', 'clothing', '헌 옷', '깨끗한 옷은 의류 수거함에, 훼손된 옷은 종량제 봉투에 넣으세요.', 'clothing', 1),
  ('delivery-container', 'plastic', '배달 플라스틱 용기', '국물과 기름기를 헹군 뒤 플라스틱으로 배출하세요. 오염이 심하면 일반쓰레기입니다.', NULL, 1),
  ('coffee-cup-paper', 'paper', '일회용 종이컵', '내용물을 비우고 물기를 제거한 뒤 종이로 배출하세요. 플라스틱 뚜껑은 분리합니다.', NULL, 1),
  ('coffee-cup-plastic', 'plastic', '일회용 플라스틱컵', '내용물을 비우고 헹군 뒤 플라스틱으로 배출하세요.', NULL, 1);

INSERT INTO waste_aliases (item_id, alias) VALUES
  ('pet-clear', '페트병'),
  ('pet-clear', '생수병'),
  ('pet-clear', '콜라병'),
  ('pet-clear', '사이다병'),
  ('pet-clear', '투명병'),
  ('pet-colored', '초록 페트'),
  ('pet-colored', '갈색 페트'),
  ('plastic-container', '플라스틱'),
  ('plastic-container', '샴푸통'),
  ('plastic-container', '세제통'),
  ('vinyl-bag', '비닐'),
  ('vinyl-bag', '봉투'),
  ('vinyl-bag', '과자봉지'),
  ('alu-can', '캔'),
  ('alu-can', '맥주캔'),
  ('alu-can', '음료캔'),
  ('steel-can', '참치캔'),
  ('steel-can', '통조림'),
  ('glass-bottle', '유리'),
  ('glass-bottle', '소주병'),
  ('glass-bottle', '맥주병'),
  ('glass-bottle', '잼병'),
  ('paper-box', '박스'),
  ('paper-box', '택배박스'),
  ('paper-box', '골판지'),
  ('newspaper', '신문지'),
  ('food-waste', '음식물'),
  ('food-waste', '남은음식'),
  ('general-waste', '종량제'),
  ('general-waste', '쓰레기'),
  ('battery', '건전지'),
  ('battery', '배터리'),
  ('medicine', '약'),
  ('medicine', '알약'),
  ('medicine', '시럽'),
  ('small-electronics', '가전'),
  ('small-electronics', '충전기'),
  ('small-electronics', '이어폰'),
  ('small-electronics', '헤어드라이어'),
  ('clothing', '옷'),
  ('clothing', '의류'),
  ('clothing', '헌옷'),
  ('delivery-container', '배달용기'),
  ('delivery-container', '배달'),
  ('delivery-container', '반찬통'),
  ('coffee-cup-paper', '종이컵'),
  ('coffee-cup-paper', '커피컵'),
  ('coffee-cup-plastic', '플라스틱컵'),
  ('coffee-cup-plastic', '카페컵');

INSERT INTO guide_steps (item_id, step_order, title, body, required) VALUES
  ('pet-clear', 1, '내용물 비우기', '남은 음료를 완전히 비우세요.', 1),
  ('pet-clear', 2, '가볍게 헹구기', '물로 한 번 헹궈 이물질을 제거하세요.', 1),
  ('pet-clear', 3, '라벨·뚜껑 분리', '비닐 라벨은 떼고, 뚜껑은 플라스틱으로 따로 모으세요.', 1),
  ('pet-clear', 4, '압착하기', '부피를 줄이도록 발로 밟거나 눌러 납작하게 만드세요.', 1),
  ('pet-clear', 5, '전용함 배출', '투명 페트 전용 수거함에 넣으세요.', 1),
  ('pet-colored', 1, '내용물 비우기', '남은 내용물을 비우세요.', 1),
  ('pet-colored', 2, '헹구기', '이물질을 헹궈 내세요.', 1),
  ('pet-colored', 3, '라벨 제거', '라벨과 뚜껑을 분리하세요.', 1),
  ('pet-colored', 4, '플라스틱 배출', '유색 페트는 투명 전용함이 아니라 플라스틱으로 배출하세요.', 1),
  ('plastic-container', 1, '음식물 비우기', '남은 내용물을 완전히 비우세요.', 1),
  ('plastic-container', 2, '헹구기', '기름기와 양념을 물로 헹구세요.', 1),
  ('plastic-container', 3, '라벨 제거', '종이·비닐 라벨을 떼세요.', 1),
  ('plastic-container', 4, '플라스틱 배출', '플라스틱 수거함에 넣으세요.', 1),
  ('vinyl-bag', 1, '이물질 제거', '음식물과 물기를 털어내세요.', 1),
  ('vinyl-bag', 2, '흩날림 방지', '여러 장을 모아 묶거나 한 봉지에 담으세요.', 1),
  ('vinyl-bag', 3, '비닐 배출', '비닐 전용 수거함에 넣으세요. 이물질이 많으면 일반쓰레기입니다.', 1),
  ('alu-can', 1, '내용물 비우기', '남은 음료를 비우세요.', 1),
  ('alu-can', 2, '헹구기', '간단히 헹궈 잔여물을 제거하세요.', 1),
  ('alu-can', 3, '압착하기', '발로 밟아 납작하게 만드세요.', 1),
  ('alu-can', 4, '캔 배출', '캔 수거함에 넣으세요.', 1),
  ('steel-can', 1, '내용물 비우기', '남은 음식을 완전히 비우세요.', 1),
  ('steel-can', 2, '헹구기', '기름기를 헹궈 내세요.', 1),
  ('steel-can', 3, '날카로운 뚜껑 주의', '따개 뚜껑은 안에 넣고 찌그러뜨리세요.', 1),
  ('steel-can', 4, '캔 배출', '캔 수거함에 넣으세요.', 1),
  ('glass-bottle', 1, '내용물 비우기', '남은 내용물을 비우세요.', 1),
  ('glass-bottle', 2, '헹구기', '가볍게 헹구세요.', 1),
  ('glass-bottle', 3, '뚜껑 분리', '금속·플라스틱 뚜껑은 재질별로 분리하세요.', 1),
  ('glass-bottle', 4, '깨지지 않게 배출', '유리 수거함에 넣으세요. 깨진 유리는 신문지에 싸 일반쓰레기로 내세요.', 1),
  ('paper-box', 1, '테이프 제거', '박스 테이프와 운송장 스티커를 떼세요.', 1),
  ('paper-box', 2, '접기', '평평하게 접어 부피를 줄이세요.', 1),
  ('paper-box', 3, '종이 배출', '종이 수거함에 넣으세요. 비닐 코팅이 많으면 일반쓰레기입니다.', 1),
  ('newspaper', 1, '물기 방지', '젖은 신문은 재활용이 어렵습니다.', 1),
  ('newspaper', 2, '묶기', '끈으로 묶거나 박스에 담으세요.', 1),
  ('newspaper', 3, '종이 배출', '종이 수거함에 넣으세요.', 1),
  ('food-waste', 1, '이물질 제거', '비닐, 뼈, 껍질(호두·조개 등)은 빼세요.', 1),
  ('food-waste', 2, '물기 제거', '물기를 꼭 짜거나 말리세요.', 1),
  ('food-waste', 3, '전용함 배출', '음식물 전용 수거함이나 공동 수거 용기에 넣으세요.', 1),
  ('general-waste', 1, '재활용 가능 여부 확인', '헹궈도 이물질이 남으면 일반쓰레기입니다.', 1),
  ('general-waste', 2, '종량제 배출', '지자체 종량제 봉투에 담아 배출하세요.', 1),
  ('battery', 1, '다른 쓰레기와 분리', '건전지는 화재·오염 위험이 있어 종량제에 넣지 마세요.', 1),
  ('battery', 2, '전용함 찾기', '아파트, 주민센터, 대형마트의 폐건전지 수거함을 이용하세요.', 0),
  ('battery', 3, '지도에서 위치 확인', '가까운 수거함은 지도 탭에서 확인할 수 있습니다.', 0),
  ('medicine', 1, '포장 정리', '알약은 시트에서 꺼내지 않아도 됩니다. 개인정보는 가리세요.', 1),
  ('medicine', 2, '절대 흘려보내지 않기', '변기·싱크대에 버리면 수질 오염의 원인이 됩니다.', 1),
  ('medicine', 3, '약국 수거함', '가까운 약국이나 보건소의 폐의약품 수거함에 제출하세요.', 1),
  ('small-electronics', 1, '개인정보 삭제', '휴대폰·태블릿은 초기화하세요.', 1),
  ('small-electronics', 2, '선 정리', '충전 케이블은 함께 모아도 됩니다.', 0),
  ('small-electronics', 3, '전용함 배출', '주민센터, 마트, 재활용 정거장의 소형가전 수거함을 이용하세요.', 1),
  ('clothing', 1, '상태 확인', '입을 수 있는 옷만 의류 수거함에 넣으세요.', 1),
  ('clothing', 2, '오염·훼손 옷', '찢기거나 심하게 오염된 옷은 종량제 봉투로 배출하세요.', 1),
  ('clothing', 3, '의류함 배출', '비 오는 날에는 젖지 않게 넣거나 다음 날을 이용하세요.', 0),
  ('delivery-container', 1, '음식물 비우기', '국물과 반찬을 완전히 비우세요.', 1),
  ('delivery-container', 2, '헹구기', '기름기가 남아 있으면 재활용이 어렵습니다.', 1),
  ('delivery-container', 3, '재질 분리', '뚜껑·본체 재질이 다르면 분리하세요.', 1),
  ('delivery-container', 4, '플라스틱 배출', '깨끗하면 플라스틱, 오염이 심하면 일반쓰레기입니다.', 1),
  ('coffee-cup-paper', 1, '내용물 비우기', '남은 음료를 비우세요.', 1),
  ('coffee-cup-paper', 2, '뚜껑·빨대 분리', '플라스틱 뚜껑과 빨대는 플라스틱으로 분리하세요.', 1),
  ('coffee-cup-paper', 3, '종이 배출', '물기를 털고 종이로 배출하세요. 코팅이 심한 컵은 일반쓰레기일 수 있습니다.', 1),
  ('coffee-cup-plastic', 1, '내용물 비우기', '남은 음료를 비우세요.', 1),
  ('coffee-cup-plastic', 2, '헹구기', '가볍게 헹구세요.', 1),
  ('coffee-cup-plastic', 3, '플라스틱 배출', '플라스틱 수거함에 넣으세요.', 1);

INSERT INTO upcycle_tips (item_id, title, body, caution) VALUES
  ('pet-clear', '페트병 화분', '병 윗부분을 자르고 흙을 담아 허브 화분으로 쓸 수 있습니다.', '자를 때 칼날을 조심하고, 어린이는 반드시 보호자와 함께 하세요.'),
  ('pet-clear', '물뿌리개', '뚜껑에 작은 구멍을 내면 간단한 물뿌리개가 됩니다.', NULL),
  ('glass-bottle', '유리병 화병', '라벨을 제거하고 깨끗이 씻으면 꽃병으로 재사용할 수 있습니다.', '깨진 유리는 사용하지 마세요.'),
  ('paper-box', '수납 박스', '튼튼한 택배박스는 덮개를 보강해 수납함으로 쓸 수 있습니다.', NULL),
  ('clothing', '에코백·걸레', '큰 티셔츠는 에코백으로, 면 티는 청소 걸레로 재탄생합니다.', '바늘을 사용할 때 주의하세요.'),
  ('delivery-container', '냉장고 보관통', '뚜껑이 맞는 깨끗한 용기는 단기 보관 용기로 재사용할 수 있습니다.', '전자레인지 사용 가능 여부를 확인하세요.');

-- 서울 시청 인근 시드 수거함 (공공데이터 연동 전 프로토타입)
INSERT INTO collection_bins (id, type, name, address, lat, lng, phone, hours, source, external_id) VALUES
  ('bin-med-1', 'medicine', '시청역 인근 온누리약국', '서울 중구 세종대로 110', 37.5663, 126.9779, '02-123-0001', '09:00–19:00', 'seed', NULL),
  ('bin-med-2', 'medicine', '을지로입구 건강약국', '서울 중구 을지로 50', 37.5660, 126.9824, NULL, '09:00–18:00', 'seed', NULL),
  ('bin-med-3', 'medicine', '명동 사랑약국', '서울 중구 명동길 14', 37.5636, 126.9850, NULL, NULL, 'seed', NULL),
  ('bin-el-1', 'electronics', '중구 재활용센터 소형가전', '서울 중구 수표로 27', 37.5678, 126.9891, '02-123-0002', '09:00–18:00', 'seed', NULL),
  ('bin-el-2', 'electronics', '시청 무인 소형가전함', '서울 중구 태평로 1가', 37.5651, 126.9769, NULL, '24시간', 'seed', NULL),
  ('bin-cl-1', 'clothing', '무교동 의류 수거함', '서울 중구 무교로 15', 37.5674, 126.9798, NULL, NULL, 'seed', NULL),
  ('bin-cl-2', 'clothing', '을지로 의류함', '서울 중구 을지로 12', 37.5658, 126.9836, NULL, NULL, 'seed', NULL),
  ('bin-rs-1', 'recycle_station', '서울광장 재활용 정거장', '서울 중구 세종대로 110', 37.5657, 126.9780, NULL, '08:00–20:00', 'seed', NULL),
  ('bin-rs-2', 'recycle_station', '청계천 재활용 정거장', '서울 중구 청계천로 40', 37.5689, 126.9860, NULL, '08:00–20:00', 'seed', NULL),
  ('bin-bat-1', 'battery', '시청역 폐건전지함', '서울 중구 세종대로 지하', 37.5655, 126.9770, NULL, '역 운영시간', 'seed', NULL),
  ('bin-bat-2', 'battery', '을지로 마트 폐건전지함', '서울 중구 을지로 30', 37.5662, 126.9810, NULL, '10:00–22:00', 'seed', NULL),
  ('bin-med-gn', 'medicine', '강남역 온누리약국', '서울 강남구 강남대로 396', 37.4980, 127.0276, NULL, '09:00–21:00', 'seed', NULL),
  ('bin-el-gn', 'electronics', '강남 소형가전 수거함', '서울 강남구 테헤란로 152', 37.5000, 127.0365, NULL, NULL, 'seed', NULL),
  ('bin-cl-hd', 'clothing', '홍대입구 의류 수거함', '서울 마포구 양화로 160', 37.5572, 126.9236, NULL, NULL, 'seed', NULL),
  ('bin-rs-sc', 'recycle_station', '신촌 재활용 정거장', '서울 서대문구 신촌로 83', 37.5565, 126.9368, NULL, '08:00–20:00', 'seed', NULL);
