-- 인식 피드백, 별칭 보강, 수거함 시드 확대
CREATE TABLE IF NOT EXISTS recognition_feedback (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  log_id TEXT,
  item_id TEXT,
  helpful INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_feedback_item ON recognition_feedback(item_id, created_at);

INSERT INTO waste_aliases (item_id, alias) VALUES
  ('pet-clear', '생수'),
  ('pet-clear', '이온음료'),
  ('pet-clear', '삼다수'),
  ('pet-colored', '초록병'),
  ('pet-colored', '포카리'),
  ('plastic-container', '샴푸'),
  ('plastic-container', '린스통'),
  ('plastic-container', '요구르트통'),
  ('vinyl-bag', '과자 봉지'),
  ('vinyl-bag', '라면봉지'),
  ('vinyl-bag', '택배비닐'),
  ('alu-can', '맥주 캔'),
  ('alu-can', '탄산캔'),
  ('steel-can', '참치'),
  ('glass-bottle', '와인병'),
  ('glass-bottle', '드링크병'),
  ('paper-box', '택배'),
  ('paper-box', '종이박스'),
  ('newspaper', '전단지'),
  ('food-waste', '남은 음식'),
  ('general-waste', '휴지'),
  ('general-waste', '마스크'),
  ('battery', '충전지'),
  ('battery', '단추전지'),
  ('medicine', '약봉지'),
  ('medicine', '처방약'),
  ('medicine', '감기약'),
  ('small-electronics', '이어폰'),
  ('small-electronics', '보조배터리'),
  ('small-electronics', '마우스'),
  ('clothing', '패딩'),
  ('clothing', '이불'),
  ('delivery-container', '배달 용기'),
  ('delivery-container', '일회용기'),
  ('delivery-container', '짜장통'),
  ('coffee-cup-paper', '일회용컵'),
  ('coffee-cup-paper', '스타벅스컵'),
  ('coffee-cup-plastic', '아이스컵'),
  ('coffee-cup-plastic', '카페 플라스틱컵');

-- 서울 외 주요 도시 시드 (공공데이터 키 없을 때도 빈 지도를 줄인다)
INSERT OR IGNORE INTO collection_bins (id, type, name, address, lat, lng, phone, hours, source, external_id) VALUES
  ('bin-med-busan', 'medicine', '서면 온누리약국', '부산 부산진구 중앙대로 672', 35.1576, 129.0590, NULL, '09:00–21:00', 'seed', NULL),
  ('bin-el-busan', 'electronics', '부산진 소형가전 수거함', '부산 부산진구 가야대로 772', 35.1570, 129.0562, NULL, NULL, 'seed', NULL),
  ('bin-cl-busan', 'clothing', '서면 의류 수거함', '부산 부산진구 서면로 68', 35.1568, 129.0584, NULL, NULL, 'seed', NULL),
  ('bin-med-incheon', 'medicine', '부평역 건강약국', '인천 부평구 부평대로 15', 37.4895, 126.7245, NULL, '09:00–20:00', 'seed', NULL),
  ('bin-el-incheon', 'electronics', '부평 소형가전함', '인천 부평구 부평대로 168', 37.4920, 126.7220, NULL, NULL, 'seed', NULL),
  ('bin-med-daegu', 'medicine', '동성로 약국', '대구 중구 동성로 2길 10', 35.8691, 128.5950, NULL, '09:00–21:00', 'seed', NULL),
  ('bin-cl-daegu', 'clothing', '반월당 의류함', '대구 중구 중앙대로 390', 35.8656, 128.5933, NULL, NULL, 'seed', NULL),
  ('bin-med-daejeon', 'medicine', '둔산 온누리약국', '대전 서구 둔산로 123', 36.3510, 127.3845, NULL, '09:00–20:00', 'seed', NULL),
  ('bin-rs-daejeon', 'recycle_station', '둔산 재활용 정거장', '대전 서구 둔산대로 100', 36.3540, 127.3840, NULL, '08:00–20:00', 'seed', NULL),
  ('bin-med-gwangju', 'medicine', '충장로 약국', '광주 동구 충장로 70', 35.1467, 126.9175, NULL, NULL, 'seed', NULL),
  ('bin-med-suwon', 'medicine', '수원역 사랑약국', '경기 수원시 팔달구 덕영대로 924', 37.2663, 127.0000, NULL, '09:00–21:00', 'seed', NULL),
  ('bin-cl-suwon', 'clothing', '수원역 의류 수거함', '경기 수원시 팔달구 매산로 1', 37.2660, 126.9996, NULL, NULL, 'seed', NULL),
  ('bin-med-songpa', 'medicine', '잠실 온누리약국', '서울 송파구 올림픽로 240', 37.5110, 127.0980, NULL, '10:00–22:00', 'seed', NULL),
  ('bin-el-songpa', 'electronics', '잠실 소형가전 수거함', '서울 송파구 올림픽로 300', 37.5135, 127.1025, NULL, NULL, 'seed', NULL),
  ('bin-bat-gn', 'battery', '강남역 폐건전지함', '서울 강남구 강남대로 396', 37.4979, 127.0276, NULL, '역 운영시간', 'seed', NULL);
